### ISSUE TITLE
[2.12.2] Bug: Error when trying to delegate to pool.

### ISSUE THREAD

**Issue by DickWhitmanBTC** [leather-io/extension#1463]
**Note: More Details & Images in the comment Below**

An error occurred while using Stacks Wallet for Web (`2.12.2`).

### Error
> Not a c32-encoded string

#### Stack trace
```bash
Error: Not a c32-encoded string
    at Object.c32decode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85504:15)
    at Object.c32checkDecode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85390:30)
    at c32addressDecode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85205:23)
    at createAddress (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:25841:93)
    at createContractCallPayload (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:25196:90)
    at makeUnsignedContractCall (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23578:98)
    at makeContractCall (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23634:35)
    at generateContractCallTx (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:48213:90)
    at _callee2$ (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:48387:151)
    at tryCatch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:141521:40)
```

**Comment by DickWhitmanBTC** [comment]
I am using the latest version with the Chrome extension.

I am getting this error when trying to join a staking pool.

**Comment by DickWhitmanBTC** [comment]
Can you only stake in one pool at a time?
