### ISSUE TITLE
[2.12.2] Bug: Error when trying to delegate to pool

### ISSUE THREAD

**Issue by DickWhitmanBTC** [leather-io/extension#1464]
**Getting this error when trying to delegate to a pool**

![error1](https://user-images.githubusercontent.com/85768073/126461795-501e57ec-0df0-4325-9e9c-b60dd4cf3a28.JPG)

An error occurred while using Stacks Wallet for Web (`2.12.2`).

### Error
> Not a c32-encoded string

#### Stack trace
```bash
Error: Not a c32-encoded string
    at Object.c32decode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85504:15)
    at Object.c32checkDecode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85390:30)
    at c32addressDecode (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:85205:23)
    at createAddress (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:25841:93)
    at createContractCallPayload (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:25196:90)
    at makeUnsignedContractCall (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23578:98)
    at makeContractCall (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:23634:35)
    at generateContractCallTx (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:48213:90)
    at _callee2$ (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:48387:151)
    at tryCatch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:141521:40)
```

**Comment by aulneau** [comment]
This error means you're passing an incorrect stacks address somewhere -- can I ask where you're calling this transaction (what app?)
