### ISSUE TITLE
Error message enchantment needed for contract call with mismatch type

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#1505]
Error message enchantment needed for contract call with mismatch type.

If the user attempt to call a contract and the parameters are incorrect the error below shows, this is the expected result but its a pretty ugly user experience. Could we possibly make this fail gracefully?

Low level issue P4

<img width="1071" alt="Screen Shot 2021-07-29 at 10 18 31 AM" src="https://user-images.githubusercontent.com/49165468/127508548-9b7d8cb8-3610-46cc-b8d1-b2cf65d0deb5.png">

An error occurred while using Stacks Wallet for Web (`2.12.2.825`).

### Error
> Invalid c32check string: checksum mismatch

#### Stack trace
```bash
Error: Invalid c32check string: checksum mismatch
    at Object.c32checkDecode (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:85528:15)
    at c32addressDecode (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:85334:23)
    at createAddress (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:25841:93)
    at createContractCallPayload (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:25196:90)
    at makeUnsignedContractCall (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:23578:98)
    at makeContractCall (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:23634:35)
    at generateContractCallTx (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:48271:90)
    at _callee2$ (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:48445:151)
    at tryCatch (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:141638:40)
    at Generator.invoke [as _invoke] (chrome-extension://fkdllpjlipgckkopglnecnddldlgnnpe/index.js:141868:22)
```

**Comment by aulneau** [comment]
> An error occurred while using Stacks Wallet for Web (2.12.2.825).

You're on a pretty old version -- I think this has actually been fixed via https://github.com/blockstack/stacks-wallet-web/commit/3f3f0ef7a8a0a7bc79e42e4fdc3de0818954904b

can you try with 2.12.4?

**Comment by markmhendrickson** [comment]
cc @timstackblock to confirm above
