### ISSUE TITLE
Fix "Unable to get origin for request" error when signing transaction 

### ISSUE THREAD

**Issue by markmhendrickson** [leather-io/extension#1545]
When trying to place a bet with https://vsbtcus.bitbucket.io/

https://forum.stacks.org/t/a-bet-dapp-base-on-stacks/12256/3

![image](https://user-images.githubusercontent.com/28991/128697192-3e7fcc90-2516-4be3-b93b-e1a4c4b8f53f.png)

An error occurred while using Stacks Wallet for Web (`2.12.4`).

### Error
> Unable to get origin for request: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJzZW5kVG9TaWduSW4iOmZhbHNlLCJhcHBEZXRhaWxzIjp7Im5hbWUiOiJ2cyIsImljb24iOiJodHRwczovL2kucG9zdGltZy5jYy9uTFNiV2dGcy9sb2dvLnBuZyJ9LCJjb25uZWN0VmVyc2lvbiI6IjYuMC4wIiwianRpIjoiMjdjNWY3ZjUtYzkyYS00YmY5LTk3NmUtYzI4NDFhN2E4Nzk3IiwiaWF0IjoxNjI4NTA2NzA5LCJleHAiOjE2Mjg1MTAzMDksImlzcyI6ImRpZDpidGMtYWRkcjoxNVA4RDZNd01YMjY0UlpvQmpNOXJWWGFwN0hhcDFYd1V5IiwicHVibGljX2tleXMiOlsiMDIzMjMxNDQxM2NkYmFjMWYzNWRiNzIxYjE1NzQzYzA1MmVmMTQxYTRkNDU1YjUzZGIyODgyMGVlMzNjN2ViMDk1Il0sImRvbWFpbl9uYW1lIjoiaHR0cHM6Ly92c2J0Y3VzLmJpdGJ1Y2tldC5pbyIsIm1hbmlmZXN0X3VyaSI6Imh0dHBzOi8vdnNidGN1cy5iaXRidWNrZXQuaW91bmRlZmluZWQiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3ZzYnRjdXMuYml0YnVja2V0LmlvLyIsInZlcnNpb24iOiIxLjMuMSIsImRvX25vdF9pbmNsdWRlX3Byb2ZpbGUiOnRydWUsInN1cHBvcnRzX2h1Yl91cmwiOnRydWUsInNjb3BlcyI6WyJzdG9yZV93cml0ZSIsInB1Ymxpc2hfZGF0YSJdfQ.zTex9AOaiASrkjejsK-m7UmGlpwZ8hAHSPsFQ-Vz6hBeay2mpXBy3BVPoDtgY8WYDfFfIjMtyTgWRY8Un7wK8A

#### Stack trace
```bash
Error: Unable to get origin for request: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJzZW5kVG9TaWduSW4iOmZhbHNlLCJhcHBEZXRhaWxzIjp7Im5hbWUiOiJ2cyIsImljb24iOiJodHRwczovL2kucG9zdGltZy5jYy9uTFNiV2dGcy9sb2dvLnBuZyJ9LCJjb25uZWN0VmVyc2lvbiI6IjYuMC4wIiwianRpIjoiMjdjNWY3ZjUtYzkyYS00YmY5LTk3NmUtYzI4NDFhN2E4Nzk3IiwiaWF0IjoxNjI4NTA2NzA5LCJleHAiOjE2Mjg1MTAzMDksImlzcyI6ImRpZDpidGMtYWRkcjoxNVA4RDZNd01YMjY0UlpvQmpNOXJWWGFwN0hhcDFYd1V5IiwicHVibGljX2tleXMiOlsiMDIzMjMxNDQxM2NkYmFjMWYzNWRiNzIxYjE1NzQzYzA1MmVmMTQxYTRkNDU1YjUzZGIyODgyMGVlMzNjN2ViMDk1Il0sImRvbWFpbl9uYW1lIjoiaHR0cHM6Ly92c2J0Y3VzLmJpdGJ1Y2tldC5pbyIsIm1hbmlmZXN0X3VyaSI6Imh0dHBzOi8vdnNidGN1cy5iaXRidWNrZXQuaW91bmRlZmluZWQiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3ZzYnRjdXMuYml0YnVja2V0LmlvLyIsInZlcnNpb24iOiIxLjMuMSIsImRvX25vdF9pbmNsdWRlX3Byb2ZpbGUiOnRydWUsInN1cHBvcnRzX2h1Yl91cmwiOnRydWUsInNjb3BlcyI6WyJzdG9yZV93cml0ZSIsInB1Ymxpc2hfZGF0YSJdfQ.zTex9AOaiASrkjejsK-m7UmGlpwZ8hAHSPsFQ-Vz6hBeay2mpXBy3BVPoDtgY8WYDfFfIjMtyTgWRY8Un7wK8A
    at getRequestOrigin (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:47774:11)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:46284:93
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:46314:7
    at fk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135807:359)
    at exports.unstable_runWithPriority (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:143860:343)
    at gg (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135667:325)
    at Oj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135806:308)
    at Lj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135788:50)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135668:115
    at exports.unstable_runWithPriority (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:143860:343)
```

**Comment by aulneau** [comment]
This typically happens when the window(extension popup) is refreshed, or the origin app didn't craft the auth request correctly.
