### ISSUE TITLE
[2.12.5] Bug: <describe issue>

### ISSUE THREAD

**Issue by vovo999** [leather-io/extension#1557]
An error occurred while using Hiro Wallet for Web (`2.12.5`).

### Error
> Cannot read property 'username' of undefined

#### Stack trace
```bash
TypeError: Cannot read property 'username' of undefined
    at getAccountDisplayName (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:33064:15)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:53359:104
    at Ch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135162:137)
    at li (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135185:154)
    at ki (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135183:169)
    at ii (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135182:178)
    at ck (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135279:126)
    at bk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135255:347)
    at ak (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135255:278)
    at Tj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:135255:138)
```

**Comment by aulneau** [comment]
@vovo999 can you describe what you were doing to get to this error?
