### ISSUE TITLE
[2.12.5] Bug: <wallet won't load>

### ISSUE THREAD

**Issue by FiatLux3301** [leather-io/extension#1559]
An error occurred while using Hiro Wallet for Web (`2.12.5`).

### Error
> Unable to fetch API data from https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP33EZE65VTTSQJF5NM6JTD1HY6XGF0D33JECGE6W/balances

#### Stack trace
```bash
Error: Unable to fetch API data from https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP33EZE65VTTSQJF5NM6JTD1HY6XGF0D33JECGE6W/balances
    at _callee$ (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:44956:21)
    at tryCatch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:141106:40)
    at Generator.invoke [as _invoke] (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:141336:22)
    at Generator.next (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:141161:21)
    at asyncGeneratorStep (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:77:24)
    at _next (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:99:9)
```

**Comment by markmhendrickson** [comment]
This URL loads for me, so this may have been a temporary issue with the underlying API. Mind trying again?
