### ISSUE TITLE
[2.14.0] Bug:Cannot read property 'username' of undefined while deploying contract on testnet

### ISSUE THREAD

**Issue by nurASingh** [leather-io/extension#1603]
An error occurred while using Hiro Wallet for Web (`2.14.0`).

### Error
> Cannot read property 'username' of undefined

#### Stack trace
```bash
TypeError: Cannot read property 'username' of undefined
    at getAccountDisplayName (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:33622:15)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:54142:104
    at Ch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136037:137)
    at li (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136060:154)
    at ki (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136058:169)
    at ii (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136057:178)
    at ck (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136154:126)
    at bk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136130:347)
    at ak (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136130:278)
    at Tj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136130:138)
```

**Comment by nurASingh** [comment]
This is what I am getting when try to deploy a contract on testnet
I am using latest version of hiro wallet
