### ISSUE TITLE
[2.14.0] Bug: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by mwacc** [leather-io/extension#1623]
An error occurred while using Hiro Wallet for Web (`2.14.0`).

### Error
> Cannot read property 'username' of undefined

#### Stack trace
```bash
TypeError: Cannot read property 'username' of undefined
    at getAccountDisplayName (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:33622:15)
    at chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:54142:104
    at Ch (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136037:137)
    at li (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136060:154)
    at ki (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136058:169)
    at ii (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136057:178)
    at ck (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136154:126)
    at bk (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136130:347)
    at ak (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136130:278)
    at Tj (chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.js:136130:138)
```

**Comment by markmhendrickson** [comment]
Thanks for the report 🙏 Did this error appear at any particular moment when using the wallet?

**Comment by liujoshua** [comment]
Same error and stack trace on 2.15.0. Minting StacksPunks

**Comment by liujoshua** [comment]
Switched to Chrome and it worked. Appears to be a Brave specific issue? @mwacc

**Comment by markmhendrickson** [comment]
I'm moving this to QA on our end so they can test Chrome vs. Brave behavior when minting a StacksPunk: https://www.stackspunks.com/

**Comment by Eshwari007** [comment]
@markmhx @mwacc @liujoshua 
Did the error was produced when user connects to Hiro wallet and attempt to purchase Stacks Punk in Market place or at All Stacks Punk.Steps on how the issue was identified will be appreciated

**Comment by markmhendrickson** [comment]
@Eshwari007 As I understand it, this issue was encountered when using Brave to mint a new Stacks Punk, not to buy from the marketplace though I don't see the option on the site anymore so they may have removed it. I'll check with the developer.

**Comment by Eshwari007** [comment]
Thank you @markmhx

**Comment by Eshwari007** [comment]
Closing the ticket as the feature is no longer available
